algoritmo "Calculo5"
// Função : Calcula a expressão aritmética
// Autor : André Ferreira
// Data : 24/02/2014
// Seção de Declarações
var
 a, b, c : inteiro
 z : real
inicio
// Seção de Comandos
   escreva("Digite o valor de A: ")
   leia(a)
   escreva("Digite o valor de C: ")
   leia(c)
   escreva("Digite o valor de D: ")
   leia(d)
   z <- a*raizQ(c-d+2*a)
   escreval("")
   escreva("O valor de Z é: ", z)
   escreval("")
fimalgoritmo
