algoritmo "Calculo4"
// Função : Calcula a expressão aritmética
// Autor : André Ferreira
// Data : 24/02/2014
// Seção de Declarações
var
 a, b, c : inteiro
 x : real
inicio
// Seção de Comandos
   escreva("Digite o valor de A: ")
   leia(a)
   escreva("Digite o valor de B: ")
   leia(b)
   escreva("Digite o valor de C: ")
   leia(c)
   x <- 0.20*c+a*exp(b,4)*2*c
   escreval("")
   escreva("O valor de X é: ", x)
   escreval("")
fimalgoritmo
